# <div align="center"> Làm quen với Pytorch </div>

## Bài 1. Tạo Tensor cơ bản 
##### Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [3]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)
print(a.shape)
print(a.size())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.Size([2, 3])
torch.Size([2, 3])


## Bài 2. Tạo các Tensor thường dùng
##### Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [4]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
f = torch.ones(5, 5) * 10
print(f)

tensor([[0.8172, 0.1438, 0.3125, 0.2865],
        [0.8961, 0.9358, 0.7858, 0.0653],
        [0.8006, 0.7232, 0.8840, 0.1818]])
tensor([[ 0.3322, -0.0882,  0.4038, -0.8788],
        [ 0.3172,  0.7724,  0.8136, -0.3515],
        [-1.0845, -0.1604,  0.6072, -0.1488]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


### Bài 3. Kiểm tra thông tin Tensor
##### Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [5]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4. Slicing và Indexing
##### Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [6]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("Shape a[1]:", a[1].shape)
print("Shape a[1:, 2:4]:", a[1:, 2:4].shape)

Original tensor:
tensor([[[ 1.6217,  0.2482, -0.6105, -0.4431,  0.5111],
         [-0.5468, -0.6397,  0.9691,  1.3376, -0.4516],
         [ 1.7406,  1.7036, -1.5306, -0.3918, -0.3877],
         [-0.6845, -0.5054, -0.3612,  0.5239,  1.0900]],

        [[ 0.5989,  2.2872, -0.4647, -0.7046, -0.7332],
         [-0.3962, -0.3587,  0.3469,  0.5639,  0.7940],
         [ 1.1083,  0.0353,  0.5788,  1.1474,  1.6941],
         [-0.4368,  0.3755,  0.4285, -0.7464,  0.6296]],

        [[ 0.4809,  0.0109,  0.1144,  1.0467,  0.5830],
         [-0.2185, -0.5180,  0.7383, -1.1225,  0.2890],
         [-0.2393,  0.5184, -0.7438, -1.0482,  0.2189],
         [ 0.1349, -0.8727,  1.3501, -1.0179,  1.0155]]])

Tensor a[1]:
tensor([[ 0.5989,  2.2872, -0.4647, -0.7046, -0.7332],
        [-0.3962, -0.3587,  0.3469,  0.5639,  0.7940],
        [ 1.1083,  0.0353,  0.5788,  1.1474,  1.6941],
        [-0.4368,  0.3755,  0.4285, -0.7464,  0.6296]])

Tensor a[1:, 2:4]:
tensor([[[ 1.1083,  0.0353,  0.5788,  1.1474,  1.6

### Bài 5. Reshape và Flatten
##### Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [7]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 1.5085,  0.0733, -0.1638, -0.6467],
        [-0.4894,  0.5511,  1.0798,  0.8392],
        [ 1.4059, -0.0747,  0.8655,  0.7476]])

Flatten:
tensor([ 1.5085,  0.0733, -0.1638, -0.6467, -0.4894,  0.5511,  1.0798,  0.8392,
         1.4059, -0.0747,  0.8655,  0.7476])

Reshape to 3 x 2 x 2:
tensor([[[ 1.5085,  0.0733],
         [-0.1638, -0.6467]],

        [[-0.4894,  0.5511],
         [ 1.0798,  0.8392]],

        [[ 1.4059, -0.0747],
         [ 0.8655,  0.7476]]])


### Bài 6. Phép toán và nhân ma trận
##### Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [8]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.4226, -2.2352,  0.7476],
        [-0.0527, -0.0279,  2.7075]])
b:
tensor([[ 1.0525, -1.6721,  0.5824],
        [-1.2633, -1.0011, -0.3944]])

a + b:
tensor([[ 0.6298, -3.9073,  1.3300],
        [-1.3160, -1.0290,  2.3131]])

a / b:
tensor([[-0.4016,  1.3367,  1.2837],
        [ 0.0417,  0.0279, -6.8651]])

a^2:
tensor([[1.7861e-01, 4.9960e+00, 5.5894e-01],
        [2.7765e-03, 7.7946e-04, 7.3307e+00]])

Matrix multiplication:
tensor([[ 3.7281,  2.4767],
        [ 1.5681, -0.9733]])


### Bài 7. Các hàm thống kê trên Tensor
##### Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [9]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.5984,  0.8829, -0.2233,  0.9919],
        [-1.5678,  0.1452,  0.7492,  0.5843],
        [ 0.7503, -0.4364, -0.8659,  0.2440]])

Mean:
tensor([-0.0730,  0.1972, -0.1133,  0.6067])

Standard deviation:
tensor([1.2967, 0.6612, 0.8131, 0.3744])

Cumulative sum:
tensor([[ 0.5984,  0.8829, -0.2233,  0.9919],
        [-0.9693,  1.0281,  0.5259,  1.5762],
        [-0.2190,  0.5917, -0.3400,  1.8202]])


### Bài 8. Autograd cơ bản
##### Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [10]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### Bài 9. Gradient Descent tìm hệ số đa thức
##### Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [11]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.7538],
        [-1.8243],
        [-0.2816]], requires_grad=True)
Learned coefficients:
tensor([[0.9998],
        [1.9817],
        [2.9576]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd
##### Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [12]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.5109, requires_grad=True)
B = tensor(4.4890, requires_grad=True)
C = tensor(3.4891, requires_grad=True)
D = tensor(2.4891, requires_grad=True)


### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
##### • Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.<br>• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.<br>• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.<br>• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.