# <div align="center"> Làm quen với Pytorch </div>

## Bài 1. Tạo Tensor cơ bản 
##### Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [39]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)
print("Shape: ", a.shape)
print("Size: ", a.size())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Shape:  torch.Size([2, 3])
Size:  torch.Size([2, 3])


## Bài 2. Tạo các Tensor thường dùng
##### Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [40]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
f = torch.ones(5, 5) * 10
print(f)

tensor([[0.3377, 0.6646, 0.4552, 0.3427],
        [0.6787, 0.9926, 0.8737, 0.6940],
        [0.8394, 0.4556, 0.1616, 0.4320]])
tensor([[ 0.9454,  1.2717, -0.1959, -0.5754],
        [-0.9838,  0.1224, -0.2629, -0.2612],
        [ 0.0548,  1.5757, -1.2179, -2.1038]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


##### Nhận xét rand() và randn(): <br>rand(): sinh ra số thực ngẫu nhiên trong khoảng [0; 1) <br>randn(): sinh ra số thực ngẫu nhiên từ -$\infty$ đến $\infty$

### Bài 3. Kiểm tra thông tin Tensor
##### Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [41]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


##### Giải thích: <br>torch.Size([2, 3, 4]) mô tả kích thước (shape) của một tensor 3 chiều trong PyTorch.<br>Có 3 số nên tensor có 3 chiều:<br>- Chiều thứ nhất: 2<br>- Chiều thứ hai: 3<br>- Chiều thứ ba: 4<br>Tổng số phần tử là: 2×3×4=24

### Bài 4. Slicing và Indexing
##### Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [42]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("Shape a[1]:", a[1].shape)
print("Shape a[1:, 2:4]:", a[1:, 2:4].shape)
b = a[2:, 3:, -2:]
print("2 phan tu cuoi cung tren chieu thu 3", b)

Original tensor:
tensor([[[ 1.6125,  0.7151,  0.9332,  2.2605,  0.9705],
         [ 1.2976,  0.1058, -0.2831, -0.6428, -1.2937],
         [ 0.7482,  1.3569, -0.6444, -0.3256,  1.8897],
         [-0.7604,  0.1687, -0.5318, -0.3121, -1.4010]],

        [[-0.7750, -1.9852, -1.1666,  0.9945,  0.8860],
         [-0.3165, -1.6867, -0.5442,  0.2609, -0.4576],
         [-0.8847,  0.9047,  0.2873, -0.7133,  0.3227],
         [-1.6385, -0.0738,  0.9870,  1.1324, -0.4137]],

        [[ 0.7612, -1.0370, -1.3754,  0.8485, -0.7921],
         [ 1.1714,  0.8225, -1.2277, -0.1195,  0.0178],
         [-1.5716,  1.5696, -0.1139, -0.8745,  0.4605],
         [-0.4494,  0.5867,  1.7688,  0.4961, -0.2045]]])

Tensor a[1]:
tensor([[-0.7750, -1.9852, -1.1666,  0.9945,  0.8860],
        [-0.3165, -1.6867, -0.5442,  0.2609, -0.4576],
        [-0.8847,  0.9047,  0.2873, -0.7133,  0.3227],
        [-1.6385, -0.0738,  0.9870,  1.1324, -0.4137]])

Tensor a[1:, 2:4]:
tensor([[[-0.8847,  0.9047,  0.2873, -0.7133,  0.3

### Bài 5. Reshape và Flatten
##### Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [43]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("So phan tu truoc khi reshape:", a.numel())

print("\nFlatten:")
print(a.ravel())
print("So phan tu:", a.numel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))
print("So phan tu:", a.numel())

print("\nReshape to 2 x 6:")
print(a.reshape(2, 6))
print("So phan tu:", a.numel())

Original:
tensor([[-0.3085,  2.1757,  1.2014,  1.0963],
        [ 0.3238, -1.0468,  1.1865,  0.0335],
        [-2.7680, -0.6623, -0.2165,  0.2891]])
So phan tu truoc khi reshape: 12

Flatten:
tensor([-0.3085,  2.1757,  1.2014,  1.0963,  0.3238, -1.0468,  1.1865,  0.0335,
        -2.7680, -0.6623, -0.2165,  0.2891])
So phan tu: 12

Reshape to 3 x 2 x 2:
tensor([[[-0.3085,  2.1757],
         [ 1.2014,  1.0963]],

        [[ 0.3238, -1.0468],
         [ 1.1865,  0.0335]],

        [[-2.7680, -0.6623],
         [-0.2165,  0.2891]]])
So phan tu: 12

Reshape to 2 x 6:
tensor([[-0.3085,  2.1757,  1.2014,  1.0963,  0.3238, -1.0468],
        [ 1.1865,  0.0335, -2.7680, -0.6623, -0.2165,  0.2891]])
So phan tu: 12


### Bài 6. Phép toán và nhân ma trận
##### Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [44]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\na * b")
print(a * b)
print("\nMatrix multiplication:")
c = a @ b.T
print(c)
print("Shape:", c.shape)

a:
tensor([[ 0.1576, -0.8545,  0.2408],
        [ 2.0235, -1.0831,  0.5807]])
b:
tensor([[ 2.0552, -0.6364, -0.4418],
        [ 0.0690,  0.7520,  0.4054]])

a + b:
tensor([[ 2.2129, -1.4909, -0.2011],
        [ 2.0925, -0.3311,  0.9861]])

a / b:
tensor([[ 0.0767,  1.3426, -0.5449],
        [29.3241, -1.4403,  1.4327]])

a^2:
tensor([[0.0249, 0.7301, 0.0580],
        [4.0947, 1.1732, 0.3373]])

a * b
tensor([[ 0.3240,  0.5438, -0.1064],
        [ 0.1396, -0.8146,  0.2354]])

Matrix multiplication:
tensor([[ 0.7614, -0.5341],
        [ 4.5915, -0.4395]])
Shape: torch.Size([2, 2])


##### Nhận xét:<br>a*b là phép nhân từng phần tử tương ứng<br>a @ b.T là phép nhân ma trận

### Bài 7. Các hàm thống kê trên Tensor
##### Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [45]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

print("\n\nThay dim=0 thanh dim=1")
print("Mean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.0678, -1.5979,  0.1189, -0.0850],
        [-1.1939, -0.2147,  0.5233, -0.5366],
        [-0.6275, -1.4925, -0.7545, -0.6426]])

Mean:
tensor([-0.5845, -1.1017, -0.0374, -0.4214])

Standard deviation:
tensor([0.6320, 0.7700, 0.6531, 0.2961])

Cumulative sum:
tensor([[ 0.0678, -1.5979,  0.1189, -0.0850],
        [-1.1261, -1.8126,  0.6422, -0.6215],
        [-1.7536, -3.3051, -0.1123, -1.2642]])


Thay dim=0 thanh dim=1
Mean:
tensor([-0.3740, -0.3555, -0.8793])

Standard deviation:
tensor([0.8205, 0.7136, 0.4127])

Cumulative sum:
tensor([[ 0.0678, -1.5301, -1.4112, -1.4962],
        [-1.1939, -1.4086, -0.8853, -1.4219],
        [-0.6275, -2.1199, -2.8744, -3.5171]])


##### Nhận xét:<br>dim=0: mean,std tính theo từng cột, cumsum cộng dồn từ trên xuống<br>dim=1: mean,std tính theo từng hàng, cumsum cộng dồn từ trái sang

### Bài 8. Autograd cơ bản
##### Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [46]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

print("doi ham y")
y = 3*x**2 + 2*x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)
doi ham y
x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(30.8000)


### Bài 9. Gradient Descent tìm hệ số đa thức
##### Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [47]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.6450],
        [-0.8076],
        [-0.0291]], requires_grad=True)
Learned coefficients:
tensor([[1.0158],
        [1.9801],
        [2.0666]], requires_grad=True)


##### optimizer.zero_grad(): xóa gradient của lần lặp trước <br>mse.backward(): dùng để tự động tính đạo hàm<br>optimizer.step(): được dùng để cập nhật các trọng số của mô hình dựa trên các gradient đã được tính toán trong quá trình lan truyền ngược 

### Bài 10. Giải hệ phương trình bằng Autograd
##### Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [48]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.4165, requires_grad=True)
B = tensor(4.5834, requires_grad=True)
C = tensor(3.5834, requires_grad=True)
D = tensor(2.5834, requires_grad=True)


##### Nhận xét: Hệ phương trình có thể có vô số nghiệm vì 4 phương trình nhưng chỉ có 3 phương trình độc lập.

### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
##### • Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.<br>• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.<br>• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.<br>• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [49]:
import torch
import numpy as np

X = torch.arange(1, 25)

print("X ban đầu:")
print(X)
print("Số phần tử:", X.numel())

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nX reshape 4x6:")
print(X_4x6)

print("\nX reshape 2x12:")
print(X_2x12)

print("\nX reshape 2x3x4:")
print(X_2x3x4)

X ban đầu:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
Số phần tử: 24

X reshape 4x6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

X reshape 2x12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

X reshape 2x3x4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


#### Tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột

In [50]:
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A =")
print(A)

print("\nB =")
print(B)

print("\nA + B =")
print(A + B)

print("\nA * B =")
print(A * B)

print("\nA / B =")
print(A / B)

# dim=0: tính theo cột
print("\nTrung bình theo cột:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn theo cột:")
print(torch.std(A, dim=0))

x = torch.tensor(2.0, requires_grad=True)

y = 2 * x**2 + 5 * x + 3

y.backward()

A =
tensor([[-6.9156e-01,  9.0644e-01, -8.6141e-01, -4.0300e-04],
        [-1.7033e+00, -1.2965e+00,  7.4671e-01,  1.8659e-01],
        [ 8.1146e-01,  1.7905e-01, -9.1304e-02, -1.0101e+00]])

B =
tensor([[ 0.2751,  1.5430, -0.2365,  0.7044],
        [-0.6791, -0.9365, -2.9065,  2.4040],
        [-1.3593, -0.2351,  0.7987,  1.8957]])

A + B =
tensor([[-0.4164,  2.4494, -1.0979,  0.7040],
        [-2.3824, -2.2330, -2.1598,  2.5906],
        [-0.5479, -0.0560,  0.7074,  0.8856]])

A * B =
tensor([[-1.9026e-01,  1.3986e+00,  2.0371e-01, -2.8387e-04],
        [ 1.1567e+00,  1.2142e+00, -2.1703e+00,  4.4856e-01],
        [-1.1030e+00, -4.2085e-02, -7.2928e-02, -1.9149e+00]])

A / B =
tensor([[-2.5137e+00,  5.8747e-01,  3.6426e+00, -5.7213e-04],
        [ 2.5082e+00,  1.3843e+00, -2.5691e-01,  7.7616e-02],
        [-5.9696e-01, -7.6174e-01, -1.1431e-01, -5.3283e-01]])

Trung bình theo cột:
tensor([-0.5278, -0.0703, -0.0687, -0.2746])

Độ lệch chuẩn theo cột:
tensor([1.2654, 1.1224, 0.8043, 0

#### Autograd

In [51]:
print("x =", x)
print("y =", y)
print("dy/dx bằng autograd =", x.grad)

manual_gradient = 4 * 2 + 5

print("dy/dx tính thủ công =", manual_gradient)

np.random.seed(42)

polynomial = np.poly1d([2, -3, 5])

N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

x_train = torch.tensor(XX, dtype=torch.float32)
y_train = torch.tensor(Y, dtype=torch.float32)

w = torch.randn(3, 1, requires_grad=True)

optimizer = torch.optim.NAdam([w], lr=0.01)

EPOCHS = 2000

for epoch in range(EPOCHS):

    # Forward
    y_pred = x_train @ w

    # Loss
    mse = torch.mean((y_train - y_pred) ** 2)

    # Backward
    optimizer.zero_grad()
    mse.backward()


    optimizer.step()

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx bằng autograd = tensor(13.)
dy/dx tính thủ công = 13


#### y = 2x^2 - 3x + 5

In [52]:
print("Hệ số tìm được:")
print(w.detach().flatten())

print("\nHệ số thực tế:")
print("[2, -3, 5]")

print("\nMSE cuối:")
print(mse.item())

Hệ số tìm được:
tensor([ 2.0170, -2.9923,  4.0895])

Hệ số thực tế:
[2, -3, 5]

MSE cuối:
0.4944912791252136
